CREATE TABLE IF NOT EXISTS photos (
  id VARCHAR(64) PRIMARY KEY,
  original_path VARCHAR(1024) NOT NULL,
  sha256 CHAR(64) NOT NULL UNIQUE,
  bytes BIGINT UNSIGNED NOT NULL,
  width INT UNSIGNED NOT NULL DEFAULT 0,
  height INT UNSIGNED NOT NULL DEFAULT 0,
  metadata_json JSON NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS tasks (
  id VARCHAR(64) PRIMARY KEY,
  request_key VARCHAR(255) NOT NULL UNIQUE,
  fingerprint CHAR(71) NOT NULL,
  photo_id VARCHAR(64) NOT NULL,
  state VARCHAR(32) NOT NULL,
  attempt INT UNSIGNED NOT NULL DEFAULT 0,
  owner VARCHAR(128) NOT NULL DEFAULT '',
  epoch BIGINT UNSIGNED NOT NULL DEFAULT 0,
  available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  lease_until TIMESTAMP(6) NULL,
  last_error VARCHAR(1024) NOT NULL DEFAULT '',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_tasks_photo FOREIGN KEY (photo_id) REFERENCES photos(id)
);

CREATE TABLE IF NOT EXISTS outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  task_id VARCHAR(64) NOT NULL,
  topic VARCHAR(128) NOT NULL,
  payload BLOB NOT NULL,
  delivered_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_outbox_task_topic (task_id, topic),
  CONSTRAINT fk_outbox_task FOREIGN KEY (task_id) REFERENCES tasks(id)
);

CREATE TABLE IF NOT EXISTS task_attempts (
  task_id VARCHAR(64) NOT NULL,
  attempt INT UNSIGNED NOT NULL,
  epoch BIGINT UNSIGNED NOT NULL,
  output_path VARCHAR(1024) NOT NULL,
  output_sha256 CHAR(64) NOT NULL,
  published_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (task_id, attempt),
  CONSTRAINT fk_attempt_task FOREIGN KEY (task_id) REFERENCES tasks(id)
);
