ALTER TABLE photos ADD COLUMN IF NOT EXISTS cache_version BIGINT UNSIGNED NOT NULL DEFAULT 1;
CREATE TABLE IF NOT EXISTS cache_invalidations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  photo_id VARCHAR(64) NOT NULL,
  delivered_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
